src/api/urls.py
from django.contrib import admin
from django.urls import path
from login import views
from django.conf.urls import url, include

from django.conf import settings
from django.conf.urls.static import static

import os

app_name = 'api'

urlpatterns = [
	path('admin/', admin.site.urls),
    path('',views.index),
    path('contact/',views.contact),
    path('logout/',views.logout),
	path('products/', include('product.urls')),
	path('login/', include('login.urls'), name='login'),
	path('register/', include('register.urls')),

    path('', include('rest_framework.urls', namespace='rest_framework'))
]

src/login/urls.py
from django.urls import path
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.auth.models import User
from login import views
from django.conf import settings
from django.conf.urls.static import static

from . import views
import os

app_name ='login'

urlpatterns = [
    path('', views.login),
    # path('',views.),
    path('', views.login, name='login'),
   
]

src/register/urls.py
from django.urls import path
from . import views
from django.contrib.auth.models import User
from django.conf import settings
from django.conf.urls.static import static

app_name = 'register'


urlpatterns = [
    path('', views.register, name='register'),
    
    path('profile/<id>',views.profile,name='profile'),
    
]

src/register/models.py
from django.db import models
import datetime


TIME_ZONE =  'Asia/Kolkata'
# Create your models here.
class User(models.Model):

	active = models.BooleanField(default=True)
	fullname = models.CharField(max_length=200)
	email = models.CharField(max_length =200, unique=True)
	mobile = models.IntegerField(default =True, unique=True)
	address = models.TextField(editable = False)
	dob = models.CharField(max_length = 100 , default = '')
	image = models.ImageField(default=None,editable = False)
	password = models.CharField(max_length =200, default ='')
	country =models.CharField(max_length =100,default = '')
	state =models.CharField(max_length = 100, default ='')
	city = models.CharField(max_length = 100 , default = '')
	gender=models.CharField(max_length=200, editable = False)
	api_key = models.TextField(editable = False)
	added_date = models.DateTimeField(auto_now_add=datetime.datetime.now())
	updated_date = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.fullname+" - "+str(self.email)+"-"+str(self.id)
		

src/register/views.py
from django.shortcuts import render
from django.http import Http404,HttpResponse
from django.shortcuts import get_object_or_404, render,redirect
from django.utils import timezone
from django import forms
from .models import User
import os
import json
from django.conf import settings
from django.http import JsonResponse

from django.views.decorators.csrf import csrf_protect
from django.template import loader
from django.views.decorators.csrf import csrf_exempt
from rest_framework.decorators import api_view
from rest_framework.decorators import parser_classes
from rest_framework.parsers import JSONParser
#from hashlib 
import hashlib




# Create your views here.

@api_view(["POST", "GET"])
@parser_classes((JSONParser,))
def register(request, format=None):
	context={}
	print("method",request.method)
	if request.method == "POST":

		print("request data",request.data)
		try:
			fullname = request.data['fullname']
			email = request.data['email']
			mobile = request.data['mobile']
			# address = request.data['address']
			# image = request.data['image']
			password = request.data['password']
			country = request.data['country']
			state = request.data['state']
			city = request.data['city']
			dob = request.data['dob']
			gender = request.data['gender']
			email = ''.join(reversed(email))
			password=password+email

			email = ''.join(reversed(email))
			print(email)
			# m=md5()
			# m.update(b"")
			 
			password= hashlib.sha1(password.encode('utf-8')).hexdigest()


			email2 = ''.join(reversed(email))
			password = password + email2
			# m=md5()
			# m.update(b"")
			print(password)


			password= hashlib.sha1(password.encode('utf-8')).hexdigest()

			user=User(fullname=fullname,email=email,mobile=mobile,password=password,country=country,state=state,city=city,dob=dob,gender=gender)
			print ("data",user)
			user.save()
			print("save data",user)
			return JsonResponse({"status":200,"message":"successfully registered",'email': user.email})
		except Exception as e:
			print("error",e)
			return JsonResponse({"status":400,"Message":"Registration Failed"})
	return render(request,'register.html',context)

def profile(request,id):
    context={}
    print('userid',id)
    user = User.objects.get(pk=id)
    context['user']=user
    return render(request, 'profile.html', context)

src/register/templates/profile.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>  
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<!-- <script type="text/javascript" src="{% static 'assets/js/newprofile.js' %}"></script> -->
<!------ Include the above in your HEAD tag ---------->
     <!--    {%  if user.image is None %}
            <img src="/media/media/insta-6.jpg" alt="Default-image-for-user-{{user.id}}" class="img-responsive " style="width: 100px">
        
            <img src="/media/{{user.image.url}}" alt="Default-image-for-user-{{user.id}}" class="img-responsive " style="width: 100px">
        {% endif  %}--> 



<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container emp-profile">
            <form method="post">
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-img">
                            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS52y5aInsxSm31CvHOFHWujqUx_wWTS9iM6s7BAm21oEN_RiGoog" alt=""/>
                            <div class="file btn btn-lg btn-primary">
                                Change Photo
                                <input type="file" name="file"/>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="profile-head">
                                    <h5>
                                        {{user.fullname}}
                                    </h5>
                                    <h6>
                                         Created on {{ user.added_date }}
                                    </h6>
                                    <!-- <p class="proile-rating">RANKINGS : <span>8/10</span></p> -->
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Timeline</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <input type="submit" class="profile-edit-btn" name="btnAddMore" value="Edit Profile"/>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-work">
                            <p>WORK LINK</p>
                            <a href="">Website Link</a><br/>
                            <a href="">Bootsnipp Profile</a><br/>
                            <a href="">Bootply Profile</a>
                            <p>SKILLS</p>
                            <a href="">Web Designer</a><br/>
                            <a href="">Web Developer</a><br/>
                            <a href="">WordPress</a><br/>
                            <a href="">WooCommerce</a><br/>
                            <a href="">PHP, .Net</a><br/>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="tab-content profile-tab" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Fullname</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{ user.fullname }}</p>
                                            </div>
                                        </div>
                                       
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Email</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{ user.email }}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Phone</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{ user.mobile}}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Address</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{ user.city }},{{ user.state }}</p>
                                            </div>
                                        </div>
                            </div>
                            <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Experience</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>Expert</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Hourly Rate</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>10$/hr</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Total Projects</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>230</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>English Level</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>Expert</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Availability</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>6 months</p>
                                            </div>
                                        </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <label>Your Bio</label><br/>
                                        <p>Your detail description</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>           
        </div>







<!-- 
         <a href="/delete/{{user.id}}" role="button" >Delete Account</a><br>
      <a href="/update/{{user.id}}" role="button" >Update Profile</a><br>
      <a href="/signin/" role="button"  onclick="clean();">logout</a> -->

src/register/templates/register.html
{% load static %}
<html>

<head>

    
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    

   
    <link rel="stylesheet" type="text/css" href="{% static 'register/css/temp.css' %}">
 
    <script type="text/javascript" src="{% static 'register/js/user.js' %}"></script>
<style type="text/css">
 #password + .glyphicon {
   cursor: pointer;
   pointer-events: all;
 }

/* Styles for CodePen Demo Only */
#wrapper {
  max-width: 500px;
  margin: auto;
  padding-top: 25vh;
}
    </style>
    <script type="text/javascript">
        $(".reveal").on('click',function() {
    var $pwd = $(".pwd");
    if ($pwd.attr('type') === 'password') {
        $pwd.attr('type', 'text');
    } else {
        $pwd.attr('type', 'password');
    }
});

    </script>
</head>
<!------ Include the above in your HEAD tag ---------->
<body>
<div class="container register">
                <div class="row">
                    <div class="col-md-3 register-left">
                        <img src="https://image.ibb.co/n7oTvU/logo_white.png" alt=""/>
                        <h3></h3>
                        <p>Welcome</p>
                        <a href="{% url 'login:login' %}">
                        <input type="submit" name="" value="Login"/></a><br/>
                    </div>
                    <div class="col-md-9 register-right">
                       <!--  <ul class="nav nav-tabs nav-justified" id="myTab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">User</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Admin</a>
                            </li>
                        --> </ul>
                        <form method="post" name="myform"  onsubmit="user(event)"> {% csrf_token %}
                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                <h3 class="register-heading">Apply as a User</h3>
                                <div class="row register-form">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input name="fullname" type="text" class="form-control" placeholder="Full Name *" value="" required />
                                        </div>
                                        
                                        <div class="form-group pass_show">
                                            <input name="password" id="password" type="password" class="form-control" placeholder="Password *" value="" title="Password must contain at least 6 characters, including UPPER/lowercase and numbers." required pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{6,}"
                                               />
                                        </div>
                                        <div class="form-group">
                                          
                                            <input name="pwd2" type="password" class="form-control"  placeholder="Confirm Password *" value="" title="Please enter the same Password as above."    onkeyup="checkpassword(this.value)" required pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{6,}" />

                                            <span class="text-danger message"></span>
                                        </div>
                                                   <div class="form-group">
                                            <input name="email" type="email" class="form-control" placeholder="Your Email *" value="" required/>
                                        </div>
                                        <div class="form-group">
                                            <div class="maxl">
                                                <label class="radio inline"> 
                                                    <input name="gender" type="radio"  value="male" checked>
                                                    <span> Male </span> 
                                                </label>
                                                <label class="radio inline"> 
                                                    <input type="radio" name="gender" value="female">
                                                    <span>Female </span> 
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                            
                                    <div class="col-md-6">

                                        <div class="form-group">
                                            <input type="text" minlength="10" maxlength="10" name="mobile" class="form-control" placeholder="Mobile *" value="" required/>
                                        </div>
                                        <div class="form-group">
                                            <input name="dob" type="date" class="form-control" placeholder="DOB *" value="" required/>
                                        </div>
                                        <div class="form-group">
                            <!-- <input name="country" type="text" class="form-control" placeholder="Country *" value="" required/> --> 
                                            <input type="text" list="country" name="country"/>
                                            <datalist id="country">
                                          <option value="India">India</option>
                                          <option value="Pakistaan">Pakistaan</option>
                                          <option value="West Indies">West Indies</option>
                                          <option value="Australia">Australia</option>
                                        </select>
</datalist>

                                        </div>
                                        <div class="form-group">
                                   <!-- <input name="state" type="text" class="form-control" placeholder="State *" value="" required/> -->
                                           <input type="text" list="state" name="state"/>
                                            <datalist id="state">
                                          <option value="Chhattisgarh">Chhattisgarh</option>
                                          <option value="Maharastra">Maharastra</option>
                                          <option value="Uttar Pradesh">Uttar Pradesh</option>
                                          <option value="Rajsthan">Rajsthan</option>
                                        </select>
</datalist>
                                        </div>
                                        <div class="form-group">
                                 <!-- <input name="city" type="text" class="form-control" placeholder="City *" value="" required/> -->
                                        <input type="text" list="city" name="city"/>
                                            <datalist id="city">
                                          <option value="Raipur">Raipur</option>
                                          <option value="Mumbai">Mumbai</option>
                                          <option value="Bilaspur">Bilaspur</option>
                                          <option value="Bhilai">Bhilai</option>
                                        </select>
</datalist>
                                        </div>

                                        <input type="submit" class="btnRegister"  value="Register" required/>
                                    </div>
                                </div>
                            </div>  </form>
                           
                        </div>
                       
                    </div>
                </div>



            </div>

    


<script type="text/javascript">
function checkpassword(re_pass)
 {
   var old_pass = $('#password').val();
   // alert(old_pass)
   if(old_pass != re_pass)
   {
     $('.message').html("Password and confirm password missmatch");
     $('.btnRegister').hide(); 
   }else{
     $('.message').html("");
     $('.btnRegister').show();
   }
 }


</script>


            </body>


</html>      